export type LANGUAGE_SET = 'LANGUAGE_SET';
export const LANGUAGE_SET: LANGUAGE_SET = 'LANGUAGE_SET';

export type LOCATION_SET = 'LOCATION_SET';
export const LOCATION_SET: LOCATION_SET = 'LOCATION_SET';
